[新 SIG 提案] deepin-system-tools
deepin-community/SIG pull request #13
Opened 2022-08-15 09:24 UTC by Angie-JA-Dou

创建原因
系统工具软件包（adduser、coreutils等）维护。

2022-08-15 09:30 UTC, BLumia requested changes

2022-08-15 09:30 UTC, BLumia commented on sig/deepin-system-tools/MEMBERS.md
> +请见 [deeepin wiki 中的小组成员页面](https://wiki.deepin.org/zh/%E5%85%B3%E4%BA%8EDeepin/Deepin_Wiki/members)
为什么引用的是 Wiki 组的成员页面？

2022-08-15 09:30 UTC, BLumia commented on sig/deepin-system-tools/README.md
> +企业微信群
不公开的吗？

2022-08-15 09:30 UTC, BLumia commented on sig/deepin-system-tools/README.md
> +- [GitHub 上的小组团队]
链接？

2022-08-17 02:37 UTC, BLumia requested changes

2022-08-17 02:37 UTC, BLumia commented on sig/deepin-system-tools/README.md
> +- http://gnu.org/software/coreutils
为什么要列软件包的官网到相关链接里，这个小组只维护这个软件包吗？

2022-08-17 02:37 UTC, BLumia commented on sig/deepin-system-tools/README.md
> +微信群
需要是公开的讨论渠道。即便是微信群也应当有加群方式，二维码或者链接之类。

2022-08-17 02:37 UTC, BLumia commented on sig/deepin-system-tools/README.md
> +活动范围：[社区论坛](https://bbs.deepin.org/)、微信群等。
维护工作的开展所位于的平台也算活动范围，比如 GitHub 的 xxx 组织或 xxx 仓库下。

2022-08-17 02:37 UTC, BLumia commented on sig/deepin-system-tools/README.md
> +* 对于向deepin贡献代码/软件包等章程请遵循deepin社区官方文档。
贡献软件包的章程/官方文档在哪？可以链接到这里并附在相关链接里。

2022-08-17 05:45 UTC, Angie-JA-Dou reviewed
update

2022-08-17 05:47 UTC, Angie-JA-Dou commented on sig/deepin-system-tools/README.md
> +- http://gnu.org/software/coreutils
不是的， 因为现在分配整理的有两个，只有一个有官网地址，所以写了一个，后续会添加更新

2022-08-17 05:47 UTC, Angie-JA-Dou commented on sig/deepin-system-tools/README.md
> +微信群
因为微信二维码仅7天有效，所以更改为了QQ群

2022-08-17 05:48 UTC, Angie-JA-Dou commented on sig/deepin-system-tools/README.md
> +* 对于向deepin贡献代码/软件包等章程请遵循deepin社区官方文档。
相关的文档还在评审中，等评审结束后更新链接

2022-08-17 05:49 UTC, Angie-JA-Dou commented on sig/deepin-system-tools/README.md
> +活动范围：[社区论坛](https://bbs.deepin.org/)、微信群等。
已修改更新

2022-08-17 07:21 UTC, BLumia commented
描述里提到需要创建 sig-deepin-system-tools，但 README 没提到哪里要用这个仓库，这个还需要创建吗？不需要的话，编辑一下描述去掉创建这个仓库的文字就行，我们不强制要求创建 SIG 对应的仓库的，但如果创建的话要在 README 提及预期的用途。

2022-08-17 07:50 UTC, Angie-JA-Dou commented
> 
需要的， 我重新更新一下README文件，写明sig-deepin-system-tools 仓库的用途。

2022-08-17 08:04 UTC, Angie-JA-Dou reviewed
update README

2022-08-17 08:04 UTC, BLumia approved these changes
稍后对应仓库创建后合入

2022-08-17 08:07 UTC, merged

2022-08-17 08:07 UTC, BLumia commented
对应仓库已创建，相关人员已邀请