新增aapt依赖
deepin-community/SIG pull request #142
Opened 2023-05-17 12:15 UTC by gfdgd-xi

新增aapt依赖

2023-05-18 01:49 UTC, tsic404 commented
仓库应该是source name 而不是 binary name。

2023-05-18 01:50 UTC, tsic404 requested changes
如上comment

2023-05-18 01:57 UTC, BLumia commented on repos.yml
> +  - repo: aapt
```suggestion
  - repo: android-platform-frameworks-base
```

然后 info 改成描述这个包的信息就可以了。

2023-05-18 13:46 UTC, BLumia commented on repos.yml
> +    info: The Android Asset Packaging Tool (aapt) takes your application resource files, such as the AndroidManifest.xml file and the XML files for your Activities, and compiles them. An R.java is al
这个包的信息也要一起更新下吧？

2023-05-18 14:10 UTC, gfdgd-xi commented on repos.yml
> +    info: The Android Asset Packaging Tool (aapt) takes your application resource files, such as the AndroidManifest.xml file and the XML files for your Activities, and compiles them. An R.java is al
info这个应该不用改吧

2023-05-18 14:44 UTC, tsic404 commented on repos.yml
> +    info: The Android Asset Packaging Tool (aapt) takes your application resource files, such as the AndroidManifest.xml file and the XML files for your Activities, and compiles them. An R.java is al
不要单介绍一个二进制，要介绍的是这个source。

2023-05-22 02:22 UTC, tsic404 approved these changes

2023-05-22 02:41 UTC, merged