[新 SIG 提案] deepin-waylandxorg
deepin-community/SIG pull request #19
Opened 2022-08-17 09:40 UTC by 1358241081

## 创建原因

deepin系统上wayland、Xorg、mesa和kwin的开发与维护。

## 仓库创建

此 SIG 需在 deepin-community 组织下创建如下仓库：

- sig-deepin-waylandxorg

2022-08-17 09:56 UTC, BLumia requested changes

2022-08-17 09:56 UTC, BLumia commented on sig/deepin-waylandxorg/README.md
> +活动范围：[deepin-community](https://github.com/deepin-community/sig-deepin-waylandxorg)、[邮件列表](deepin-waylandxorg-team@freelists.org)
确认下，deepin-waylandxorg-team 这个邮件列表还在创建过程中对吗？

2022-08-17 09:56 UTC, BLumia commented on sig/deepin-waylandxorg/README.md
> +# deepin-waylandxorg SIG
这里可以写中文的，不必拘于 Xxx SIG 的格式。另外关于小组 ID（文件夹名），wayland 与 xorg 中间加个连字符可能好点？

2022-08-17 09:56 UTC, BLumia commented on sig/deepin-waylandxorg/README.md
> +目前讨论渠道仅限于[此项目](https://github.com/NSUTanghaixiang/SIG/tree/master/sig/deepin-waylandxorg)和 [邮件列表 ](https://www.freelists.org/list/deepin-waylandxorg)。
”此项目“对应的链接不对吧。按我理解应该是小组对应的仓库，即相关链接里提供的那个仓库吧。上面也有个相同问题的地方。

2022-08-18 02:01 UTC, 1358241081 commented on sig/deepin-waylandxorg/README.md
> +目前讨论渠道仅限于[此项目](https://github.com/NSUTanghaixiang/SIG/tree/master/sig/deepin-waylandxorg)和 [邮件列表 ](https://www.freelists.org/list/deepin-waylandxorg)。
已经修改完成

2022-08-18 02:01 UTC, 1358241081 commented on sig/deepin-waylandxorg/README.md
> +活动范围：[deepin-community](https://github.com/deepin-community/sig-deepin-waylandxorg)、[邮件列表](deepin-waylandxorg-team@freelists.org)
已经创建完成

2022-08-18 02:02 UTC, 1358241081 commented on sig/deepin-waylandxorg/README.md
> +# deepin-waylandxorg SIG
小组ID已做修改，在wayland与xorg间加了“-”

2022-08-18 11:58 UTC, BLumia approved these changes
相关仓库已建立，相关人员已邀请。

2022-08-18 11:58 UTC, merged