[新 SIG 提案]Deepin gcc Team
deepin-community/SIG pull request #26
Opened 2022-08-18 02:17 UTC by hengdinx

Signed-off-by: Ding Heng <dingheng@uniontech.com>

2022-08-18 08:44 UTC, BLumia requested changes
PR 描述要写一下创建原因，小组 ID 可以看看要不要调整一下（gcc-packaging 或者其它合适的）以及如果需要创建 `sig-小组ID` 仓库的话可以列在描述里（可选的）

2022-08-19 02:23 UTC, BLumia requested changes
最后几个小问题

2022-08-19 02:23 UTC, BLumia commented on sig/gcc/README.md
> +- [邮件列表](https://www.freelists.org/list/deepin-gcc-team)
这个邮件列表是还没创建还是创建过程中？

2022-08-19 02:23 UTC, BLumia commented on sig/gcc/README.md
> +# gcc SIG
这里标题是给社区贡献者看的，可以写中文的，不必拘于 Xxx SIG 的格式

2022-08-19 02:23 UTC, BLumia commented on sig/gcc/README.md
> +- [deepin gcc SIG](https://github.com/orgs/deepin-community/teams/sig-gcc-packaging)
```suggestion
- [deepin gcc SIG](https://github.com/deepin-community/sig-gcc-packaging)
```

团队链接对外（非组织内的成员）是不可见的，建议链接到别的地方。

2022-08-19 02:23 UTC, BLumia commented on sig/gcc/MEMBERS.md
> +- [zhoupeng](zhoupeng@uniontech.com)
两位管理员需要都有 GitHub 账号

2022-08-19 03:31 UTC, hengdinx commented on sig/gcc/README.md
> +- [邮件列表](https://www.freelists.org/list/deepin-gcc-team)
刚申请, 还在审核

2022-08-22 01:54 UTC, BLumia commented on sig/gcc/README.md
> +# gcc SIG
这里还没调整呀，以及改叫 gcc-packaging 的话，文件夹名字也要改一下。

2022-08-22 01:55 UTC, BLumia commented
最后一次提到的小问题有没解决的就点 resolved 的情况，需要改完...

2022-08-22 02:24 UTC, hengdinx commented
已修改

2022-08-22 05:05 UTC, BLumia commented
> 改叫 gcc-packaging 的话，文件夹名字也要改一下。

最后一个问题了，文件夹名需要和小组名一致。现在文件夹名字还是 `gcc`。

2022-08-24 02:56 UTC, hengdinx commented
I have read the CLA Document and I hereby sign the CLA.

2022-08-24 08:48 UTC, BLumia commented on sig/gcc-packaging/README.md
> +- [deepin SIG](https://github.com/orgs/deepin-community/)
```suggestion
- [GCC 打包维护 SIG 对应的小组仓库](https://github.com/deepin-community/sig-gcc-packaging)
```

2022-08-24 08:52 UTC, BLumia approved these changes
相关小组已创建，相关人员已邀请

2022-08-24 08:53 UTC, merged