[新 SIG 提案] deepin-glibc
deepin-community/SIG pull request #32
Opened 2022-08-19 06:41 UTC by wxp19831104

## 创建原因

创建deepin-glibc。

## 仓库创建

此 SIG 需在 deepin-community 组织下创建如下仓库：

- sig-deepin-glibc

2022-08-19 07:42 UTC, BLumia requested changes

2022-08-19 07:42 UTC, BLumia commented on sig/deepin-glibc/README.md
> +- [GitHub 上的小组团队](https://github.com/orgs/deepin-community/teams/sig-deepin-systemd)
sig-deepin-systemd 肯定不对。

```suggestion
- [GitHub 上的小组对应仓库](https://github.com/deepin-community/sig-deepin-glibc/)
```

2022-08-19 07:42 UTC, BLumia commented on sig/deepin-glibc/README.md
> +2. 订阅邮件列表
邮件列表呢？

2022-08-19 11:59 UTC, BLumia reviewed
没有其它问题了，但合并前还是要确认下邮件列表的状态

2022-08-19 11:59 UTC, BLumia commented on sig/deepin-glibc/README.md
> +2. 订阅邮件列表 [deepin-glibc](deepin-glibc@freelists.org)
确认一下，邮件列表目前是创建中的状态吗？
```suggestion
2. 订阅邮件列表 [deepin-glibc](https://www.freelists.org/list/deepin-glibc)
```

2022-08-22 01:35 UTC, wxp19831104 commented on sig/deepin-glibc/README.md
> +2. 订阅邮件列表 [deepin-glibc](deepin-glibc@freelists.org)
是的。已创建

2022-08-22 01:46 UTC, BLumia approved these changes
相关仓库已创建，相关人员已邀请

2022-08-22 01:48 UTC, BLumia approved these changes
相关仓库已创建，相关人员已邀请

2022-08-22 01:48 UTC, merged