[新 SIG 提案] Deepin input method Team
deepin-community/SIG pull request #33
Opened 2022-08-19 06:46 UTC by guonafu

* fix: 添加输入法sig成员

    添加输入法sig成员

    Log: 添加输入法sig成员

    * Update README.md

    * Update README.md

    更新仓库地址

    * Update README.md

    修改仓库名字

2022-08-19 07:49 UTC, BLumia requested changes
README 有提到加入，但没看到哪里有加入方式呀，是在所描述的 Issue 区域开 Issue 表明想要加入小组的方式吗？相应的实际方式的描述建议补充到 README 中。

2022-08-19 07:49 UTC, BLumia commented on sig/deepin-input-method/README.md
> +# deepin-input-method SIG
这里是让社区贡献者看的，可以是中文，不用拘于 Xxx SIG 的形式

2022-08-19 07:49 UTC, BLumia commented on sig/deepin-input-method/README.md
> +在[deepin-grub](https://github.com/deepin-community/sig-deepin-input-method)项目的[ISSUE区](https://github.com/deepin-community/sig-deepin-input-method/issues)进行主要讨论。
```suggestion
在[sig-deepin-input-method](https://github.com/deepin-community/sig-deepin-input-method)项目的[ISSUE区](https://github.com/deepin-community/sig-deepin-input-method/issues)进行主要讨论。

```

2022-08-19 07:49 UTC, BLumia commented on sig/deepin-input-method/README.md
> +- [GitHub - [GitHub 上的小组团队](https://github.com/orgs/deepin-community/teams/sig-deepin-input-method)
```suggestion
- [GitHub 上的小组仓库](https://github.com/deepin-community/sig-deepin-input-method/)
```

2022-08-19 07:49 UTC, BLumia commented on sig/deepin-input-method/MEMBERS.md
> +- [guonafu](https://github.com/guonafu) ([微博](#)) ([Gitee](#))
```suggestion
- [guonafu](https://github.com/guonafu)
```

2022-08-24 06:08 UTC, BLumia commented on sig/deepin-input-method/README.md
> +1. 在[sig-deepin-input-metthod](https://github.com/deepin-community/sig-deepin-input-method/issues)提交issues 说明想加入的原因
```suggestion
1. 在[sig-deepin-input-method](https://github.com/deepin-community/sig-deepin-input-method/issues)提交issues 说明想加入的原因
```

2022-08-24 06:08 UTC, BLumia commented on sig/deepin-input-method/README.md
> +
```suggestion

- [GitHub 上的小组仓库](https://github.com/deepin-community/sig-deepin-input-method/)
```

2022-08-24 06:11 UTC, BLumia requested changes
两个小问题我这边直接改过了，差一个问题，提到了邮件列表但没放邮件列表的链接，是没创建还是只是忘记贴链接了？

2022-08-24 06:11 UTC, BLumia commented on sig/deepin-input-method/README.md
> +2. 订阅邮件列表
邮件列表已经创建完成了吗？链接在哪？

2022-08-24 10:23 UTC, guonafu commented on sig/deepin-input-method/README.md
> +2. 订阅邮件列表
使用公共的https://www.freelists.org/list/deepin-devel 吧

2022-08-25 01:54 UTC, BLumia commented on sig/deepin-input-method/README.md
> +
```suggestion
```

在 deepin-devel 公示输入法组成员的加入似乎不太合适。已经有 sig-deepin-input-method 仓库的话，用这个仓库就可以了

2022-08-25 01:58 UTC, BLumia approved these changes
相关仓库已创建，相关人员已邀请。

2022-08-25 02:00 UTC, BLumia commented
PR 描述我就直接编辑了。

2022-08-25 02:00 UTC, merged