[新 SIG 提案] deepin-shared-libs
deepin-community/SIG pull request #382
Opened 2023-08-23 17:42 UTC by ziggy1030

## 创建原因

  在V20系列(Debian Buster)已经基本不做功能更新，但仍有大量用户和商业产品对新版本运行库的需求下，将日常开发、编译、适配等业务工作中编译好的动态库(Share Libraries)作为副产品提供给开源社区共享使用。一来可以缓解系统仓库各类运行库版本过老的问题，同时也可以充分利用各开发者的开放资源和"副产品"，优化社区协作表现。
  将在日常开发、编译、适配等业务工作中编译好的动态库(Share Libraries)打包(如Qt、KDE Framework)，面向各大开发者、开源社区共享。

## 仓库创建

- deepin-shared-libs

2023-08-24 01:16 UTC, BLumia commented on sig/deepin-shared-libs/metadata.yml
> +    id: 39146681
创建 SIG 需要满足创建时至少有两位 SIG 成员 :)

2023-08-24 02:01 UTC, ziggy1030 commented on sig/deepin-shared-libs/metadata.yml
> +    id: 39146681
> 创建 SIG 需要满足创建时至少有两位 SIG 成员 :)

New member added

2023-08-24 02:18 UTC, BLumia commented
一些问题 :)

1. 这里的“编译好的动态库”是怎样的形式提供的，单独的 deb 包？独立的软件仓库？
2. 这里目标所提供支持的版本仅是 v20 吗？还是说实际上一并会支持 v23 或者仅支持 v23？如果后者的话，考虑直接参与 v23 的打包维护吗？
3. 交流方式会仅提供 QQ 群吗？会考虑使用 matrix 作为交流方式吗？（这样和 v23 仓库维护的贡献者/维护人员的沟通也会更方便）

2023-08-24 02:21 UTC, ziggy1030 commented
> 

1.直接用tar.xz发布，短期不考虑按照传统模式拆包成deb，因为这样在二次编译引用的时候直接export整个目录就方便很多
2.兼容V20只是有了创建的资源机遇，V23如果后续是主流发展方向可以考虑，但原则上还是尽量要保持向下兼容以免出现gcc等兼容问题
3.根据现在我的精力，暂时还是先创建一个QQ群试试水，这样门槛的话可能相对会比较低，目前是初创阶段。

2023-08-24 02:55 UTC, ziggy1030 commented
> 一些问题 :)
> 
>     1. 这里的“编译好的动态库”是怎样的形式提供的，单独的 deb 包？独立的软件仓库？
> 
>     2. 这里目标所提供支持的版本仅是 v20 吗？还是说实际上一并会支持 v23 或者仅支持 v23？如果后者的话，考虑直接参与 v23 的打包维护吗？
> 
>     3. 交流方式会仅提供 QQ 群吗？会考虑使用 matrix 作为交流方式吗？（这样和 v23 仓库维护的贡献者/维护人员的沟通也会更方便）

1.直接用tar.xz发布，短期不考虑按照传统模式拆包成deb，因为这样在二次编译引用的时候直接export整个目录就方便很多
2.兼容V20只是有了创建的资源机遇，V23如果后续是主流发展方向可以考虑，但原则上还是尽量要保持向下兼容以免出现gcc等兼容问题
3.根据现在我的精力，暂时还是先创建一个QQ群试试水，这样门槛的话可能相对会比较低，目前是初创阶段。

2023-08-24 02:56 UTC, BLumia commented
感觉听上去并不是比较理想的开发实践（比如实际上并不鼓励这种形式使用 binary library，以及类似 [hunter](https://hunter.readthedocs.io/)、[conan](https://conan.io/)、[vcpkg](https://vcpkg.io/) 以及 [meson wrap](https://mesonbuild.com/Wrap-dependency-system-manual.html) 的方案是否可以解决开发过程中的依赖构建问题等），需要进一步聊一聊。

印象里您是在 WHLUG 群的成员对吧？这次 LUG 会参加吗，如果会的话，线下讨论下，然后讨论结束后我们把结论同步到这个 issue 下面？

2023-08-24 03:26 UTC, ziggy1030 commented
> 

我下个月应该会过去，创建这个SIG并不是说有明确目标要做到什么效果，主要是用来利用一些编译中产生的可循环利用的资源和交流经验。

2023-08-25 10:01 UTC, BLumia commented
资源循环利用是可以的，只是纯构建 binary 供纯手动链库的方式存在很多方面的问题，例如自行构建的库存在多层级依赖时的依赖更新问题（如何确保 ABI 不 break/如何确保该 rebuild 的依赖进行了 rebuild）、开发库如何确保在不影响可移植性的情况下找到并链接自行构建的二进制、怎样分发编译好的二进制来确保构建工具的正确利用并满足许可协议等。

我蛮赞成展开相关的讨论的，不过希望我们在确认有一个满足需求且实践方式上没有很大问题的形式后再进行 SIG 的创建 :)

2023-09-14 06:49 UTC, BLumia approved these changes
上个月的 TC 例会已经确认此 SIG 可成立。

关于小组产出的共享库的提供形式之类技术话题，则建议后续深入展开讨论 :)

2023-09-14 06:51 UTC, BLumia commented on sig/deepin-shared-libs/metadata.yml
> +    - deepin-shared-libs
一个待确认：这个是放产出的还是放小组博客的？后者的话需要带 sig- 前缀

2023-09-14 06:53 UTC, BLumia requested changes

2023-09-14 06:53 UTC, BLumia commented on sig/deepin-shared-libs/readme_zh-CN.md
文件名： README.zh_CN.md 或者 README.zh-CN.md （目前建议前者

2023-09-24 14:03 UTC, BLumia reviewed
一些简要说明：

- README.md 是必须的
- README.zh_CN.md 是可选的，如果不打算提供多语言版本的话，README.md 也可以是中文的
- MEMBERS.md 是必须的
- metadata.yml 是必须的

其它小组内的相关文档建议放在小组自己的仓库里（仓库位置在 README 里有说明就可以，需要的话可以在这个组织下创建包含 `sig-` 前缀的仓库），这样的话，小组更新自己的文档说明就不再需要 TC 来 review 了。

2023-10-29 07:37 UTC, Rabenda commented on sig/deepin-shared-libs/README.md
> +QQ交流群、Github小组仓库Issues板块
讨论渠道不认可QQ群和微信 请更换更开放的渠道

2023-11-09 09:42 UTC, BLumia commented on sig/deepin-shared-libs/README.md
> +QQ交流群、Github小组仓库Issues板块
申请人已更新讨论渠道为“Github小组仓库Issues、Discussion板块”。

2023-11-09 09:44 UTC, merged

2023-11-09 09:46 UTC, BLumia commented
记录：

所有修改建议均已解决，仓库 sig-deepin-shared-libs 已创建，加入组织后会自动获得仓库的相关权限。

由于不确定此仓库是要存放文档还是博客，所以没有使用 sig 的博客模板。如果希望使用 Pages 功能的话，准备好后告知我就可以。

2023-11-09 19:17 UTC, Rabenda commented
> 记录：
> 
> 所有修改建议均已解决，仓库 sig-deepin-shared-libs 已创建，加入组织后会自动获得仓库的相关权限。
> 
> 由于不确定此仓库是要存放文档还是博客，所以没有使用 sig 的博客模板。如果希望使用 Pages 功能的话，准备好后告知我就可以。

合并提交了19个commit 我认为这个合并不合理 没有合理使用rebase清理提交

2023-11-10 02:03 UTC, BLumia commented
> 合并提交了19个commit 我认为这个合并不合理 没有合理使用rebase清理提交

我还刻意的选的 squash... 提交与修改记录在此 PR 里都看得到，并且 GitHub 不会主动 git gc :joy:

后续你认为这些应当创建合并提交的形式合并，以保留 PR 的修改历史？