sig: trans deepin-riscv64 to deepin-ports
deepin-community/SIG pull request #383
Opened 2023-08-28 16:01 UTC by Rabenda

deeepin-riscv64 sig 转变为 deepin-ports sig

负责内容扩大到 riscv64/loong64

cc @Zeno-sole @YukariChiba @UTsweetyfish

2023-08-29 01:36 UTC, BLumia commented on sig/deepin-ports/events.yaml
这个文件不需要动，应该在合入后会自动更新。

@myml 目前的相关 CI 可以应对 SIG 改名的情况吧？

2023-08-29 01:47 UTC, UTsweetyfish approved these changes
LGTM

2023-08-29 03:26 UTC, Zeno-sole commented
/lgtm

2023-08-29 03:59 UTC, wineee requested changes

2023-08-29 03:59 UTC, wineee commented on sig/deepin-ports/README.md
> +[邮件列表](https://www.freelists.org/list/deepin-ports)
新的邮件列表地址未建立

2023-08-29 04:05 UTC, wineee commented on sig/deepin-ports/README.md
> +目标： 为 deepin 操作系统适配 riscv64/loong64 架构, 为 riscv/loongarch 架构芯片提供更多的桌面应用。
上面用的 loong64， 此处用 loongarch，请统一描述

2023-08-29 04:06 UTC, wineee requested changes

2023-08-29 04:06 UTC, wineee commented on sig/deepin-ports/README.md
> +目标： 为 deepin 操作系统适配 riscv64/loong64 架构, 为 riscv/loongarch 架构芯片提供更多的桌面应用。
riscv64/loong64 还是 riscv/loongarch 架构，应该统一描述

2023-08-29 04:30 UTC, Rabenda commented on sig/deepin-ports/README.md
> +目标： 为 deepin 操作系统适配 riscv64/loong64 架构, 为 riscv/loongarch 架构芯片提供更多的桌面应用。
> riscv64/loong64 还是 riscv/loongarch 架构，应该统一描述

不应该统一描述 前者是在debian上的dpkg的精确描述 后者是泛指的架构描述 所以后者用了芯片字样

2023-08-29 04:31 UTC, Rabenda commented on sig/deepin-ports/events.yaml
删除了之前不活跃的用户

2023-08-29 07:25 UTC, YukariChiba commented on sig/deepin-ports/metadata.yml
> +matrix: '#deepin-ports:matrix.org'
matrix room 尚未更名

2023-08-29 18:29 UTC, Rabenda commented
> LGTM

SIG的LGTM还是只能由TC处理吧
这个涉及到改名 原来的SIG管理员也可以给出相关意见

2023-08-30 01:15 UTC, BLumia commented on sig/deepin-ports/metadata.yml
> +matrix: '#deepin-ports:matrix.org'
可以由房间管理员加个房间别名 :)

2023-08-30 07:44 UTC, Rabenda commented on sig/deepin-ports/metadata.yml
> +matrix: '#deepin-ports:matrix.org'
房间local address已修改

2023-08-30 10:13 UTC, UTsweetyfish commented
> SIG的LGTM还是只能由TC处理吧 这个涉及到改名 原来的SIG管理员也可以给出相关意见

同意成为小组成员 :)

2023-09-01 02:47 UTC, BLumia commented on sig/deepin-ports/events.yaml
合入后 @myml 的脚本应该会自动给这些人加 leave event 的。

2023-09-12 03:49 UTC, YukariChiba commented on sig/deepin-ports/README.md
> +[邮件列表](https://www.freelists.org/list/deepin-ports)
现已建立。

2023-09-12 05:08 UTC, Zeno-sole commented
/lgtm

2023-09-21 05:01 UTC, merged