Add deepin translation sig
deepin-community/SIG pull request #391
Opened 2023-11-20 08:56 UTC by Geogehuo

2023-11-20 09:06 UTC, BLumia requested changes
请参照修改

2023-11-20 09:06 UTC, BLumia commented on sig/deepin-translation-program/README.md
> +## 小组简介
如果面向的是英语用户的话，可以使用英文模板：

https://github.com/deepin-community/SIG/blob/master/sig/.template/README.md?plain=1#L12

2023-11-20 09:06 UTC, BLumia commented on sig/deepin-translation-program/README.md
> +This is the sig for deepin translation.
这里的翻译包括英文原始文案（写在代码里的）以及对应的中文文案的翻译吗？如果不包含的话建议额外明确说明这些不在范畴内的语言。

2023-11-20 09:06 UTC, BLumia commented on sig/deepin-translation-program/README.md
> +- [deepin Facebook Group](https://www.facebook.com/groups/mydeepinlinux/?mibextid=oMANbw)
小组成员需要直接加入 Transifex 进行翻译的贡献吗？需要的话，Transifex 的链接也可以贴一下。不需要的话可忽略此评注。

2023-11-20 09:06 UTC, BLumia commented on sig/deepin-translation-program/metadata.yml
> +    id:
```suggestion
    id: 88325386
```

2023-11-20 09:06 UTC, BLumia commented on sig/deepin-translation-program/metadata.yml
> +    id:
```suggestion
    id: 88325386
```

2023-11-20 09:06 UTC, BLumia commented on sig/deepin-translation-program/metadata.yml
> +    id:
```suggestion
```

另外如果这个 metadata 文件里不足两人的话，需要主动提供 MEMBERS.md 然后在里面写下当前的小组成员（至少需要有两人）

2023-11-20 09:06 UTC, BLumia commented on sig/deepin-translation-program/metadata.yml
> +  package:
```suggestion
```

2023-11-24 01:51 UTC, BLumia approved these changes

2023-11-28 02:21 UTC, Zeno-sole approved these changes

2023-12-01 11:36 UTC, RevySR approved these changes

2023-12-04 03:18 UTC, merged

2023-12-04 03:21 UTC, BLumia commented
记录：

所有修改建议均已解决，仓库 sig-deepin-translation-program 已创建，加入组织后会自动获得仓库的相关权限。