[新 SIG 提案]deepin-ThemeDsign
deepin-community/SIG pull request #394
Opened 2023-12-22 06:52 UTC by thatleosky

## 创建原因
创建 Deepin-ThemeDsign 小组的目的是为了促进个性化系统主题设计与分享。我们致力于打造一个开放、创新的社区，鼓励成员通过原创设计和非原创打包为 Deepin 用户提供更多元、独特的外观体验。通过维护主题打包工具和组织各类活动，我们希望丰富 Deepin 社区的主题资源，同时为对个性美化感兴趣的用户提供一个交流学习的平台。这一小组将成为一个贡献者荣誉加持、自由任务和设计分享的空间，为 Deepin 用户带来更丰富的社区体验。

2023-12-25 02:29 UTC, BLumia requested changes

2023-12-25 02:29 UTC, BLumia commented on sig/deepin-ThemeDsign/README.md
> +#Deepin-ThemeDsign 深度主题工坊
```suggestion
# deepin-theme-design 深度主题工坊
```

一级标题的 `#` 符号后需要有空格，不然会不起作用，可在[这里](https://github.com/deepin-community/SIG/blob/f409cd13b52d7af07e6a5ef9d99549e3f031fe9b/sig/deepin-ThemeDsign/README.md)预览你当前提交的效果。

另外，根据深度的[品牌专有名词指导方针](https://wiki.deepin.org/%E5%93%81%E7%89%8C%E4%B8%93%E6%9C%89%E5%90%8D%E8%AF%8D%E6%8C%87%E5%AF%BC%E6%96%B9%E9%92%88)，deepin 一词单独表示深度发行版时，首字母始终使用小写，即应当使用 deepin 而不是 Deepin。

以及”设计“的正确拼写方式是"design"而不是"dsign"。

2023-12-25 02:29 UTC, BLumia commented on sig/deepin-ThemeDsign/metadata.yml
文件夹的名字也需要改

2023-12-25 02:29 UTC, BLumia commented on sig/deepin-ThemeDsign/metadata.yml
> +    - sig-Deepin-ThemeDsign
如果这个仓库是用来放小组博客的话，可以考虑把 blog 和 rss 一栏也填上，填法可以参照[这个](https://github.com/deepin-community/SIG/blob/master/sig/dde-porting/metadata.yml#L3-L4)。

如果不是打算当小组博客仓库使用的话，可以忽略此评注。

2023-12-25 02:29 UTC, BLumia commented on sig/deepin-ThemeDsign/metadata.yml
> +matrix: ‘#deepin-themedsign:matrix.org’
```suggestion
matrix: '#deepin-themedsign:matrix.org'
```

引号是英文半角单引号，不分上下引号。

2023-12-25 02:29 UTC, BLumia commented on sig/deepin-ThemeDsign/metadata.yml
> +name: Deepin-ThemeDsign
这个名称可以写成适合人去阅读的名称，不必存在下划线，允许空格，希望的话也允许存在中文。

2023-12-25 02:29 UTC, BLumia commented on sig/deepin-ThemeDsign/README.md
> +欢迎来到 Deepin-ThemeDsign，我们是一个致力于促进个性化系统主题设计与分享的兴趣小组。我们致力于为用户提供更丰富、多样的外观体验。我们支持原创设计与非原创打包，以便为用户提供更多元的选择。
这个名字请确定一下。比如上面提到 deepin 首字母问题以及 Dsign 是否是错误拼写。确认后需要更新整个提交中所包含的此名称（包括文件夹名），调整为确认无误的名称。

2023-12-25 02:29 UTC, BLumia commented on sig/deepin-ThemeDsign/README.md
> +## 活动范围与目标
```suggestion
## 活动范围与目标

```

为了确保各种 Markdown 渲染引擎都可以恰当渲染，建议在标题的上下保留一个空行

2023-12-25 02:29 UTC, BLumia commented on sig/deepin-ThemeDsign/README.md
> +● 组织不定期的设计比赛，鼓励成员们展现创意，同时为获奖者提供荣誉与奖励。
```suggestion
- 不定期举办主题设计分享会，介绍最新的设计趋势、技巧与应用。

- 提供设计指导，帮助初学者快速上手个性化主题设计。

- 创建线上论坛或社交群组，方便成员之间的交流与资源分享。

- 组织不定期的设计比赛，鼓励成员们展现创意，同时为获奖者提供荣誉与奖励。
```

使用 `- ` 表示列表项，会被 Markdown 自动识别并渲染为无序列表，可以帮助屏幕阅读器之类的用户更方便的理解段落含义。

2023-12-25 02:29 UTC, BLumia commented on sig/deepin-ThemeDsign/README.md
> +## 小组章程
```suggestion
## 小组章程

```

2023-12-25 02:29 UTC, BLumia commented on sig/deepin-ThemeDsign/README.md
> +欢迎所有对 Deepin 主题美化感兴趣的爱好者加入我们的行列！已加入成员可以在 Matrix 房间中或是微信群分享经验并进行交流。
```suggestion
欢迎所有对 deepin 主题美化感兴趣的爱好者加入我们的行列！已加入成员可以在 Matrix 房间中或是微信群分享经验并进行交流。
```

其它相同用法都需要调整。

2023-12-25 02:29 UTC, BLumia commented on sig/deepin-ThemeDsign/README.md
> +[matrix:Deepin-ThemeForge](https://matrix.to/#/#deepin-themedsign:matrix.org)
这里是否要改取决于小组自身的想法。如果小组只会使用到一个 matrix 房间的话，建议这里贴单独的房间而不是 space 的名字。如果小组会有多个讨论房间且都会放置到这个 space 下的话，这里可以不改。

2023-12-25 02:29 UTC, BLumia commented on sig/deepin-ThemeDsign/README.md
> +- [GitHub 上的小组仓库](https://github.com/thatleosky/Deepin-ThemeDsign)
```suggestion
```

写重复了。

2023-12-25 03:43 UTC, thatleosky commented on sig/deepin-ThemeDsign/README.md
> +[matrix:Deepin-ThemeForge](https://matrix.to/#/#deepin-themedsign:matrix.org)
感谢提醒  我的初步想法是主题和壁纸等几乎不涉及到代码  我们初步的想法是主要使用deepin论坛或者是微信等工具会更加高效  论坛的地址我已经贴出 微信群的话请问您有什么好建议吗？

2023-12-27 02:55 UTC, BLumia approved these changes
matrix 群的方式如果保留的话，记得多关注 matrix 群。如果平实不打算关注的话，可以考虑移除 matrix 群的联系方式，并更换到别的实际在用的联系方式上。

其它我这边 ok 。

2023-12-28 07:54 UTC, shiptux approved these changes

2023-12-28 07:59 UTC, Zeno-sole approved these changes

2023-12-28 08:41 UTC, merged