[新SIG提案] deepin-security SIG
deepin-community/SIG pull request #420
Opened 2024-05-23 10:12 UTC by jingfelix

## 创建原因

创建 deepin-security SIG 的目的在于保护与提升 deepin 的系统安全性。我们通过静态检测，模糊测试等方式，对deepin 内核与系统组件进行测试，帮助查找系统中的漏洞。同时，通过对使用的安全组件配置和安全规则提出合理的建议，我们帮助提升 deepin 的系统安全性。

2024-05-24 03:00 UTC, BLumia requested changes
Security 是一个很严肃的事情。`deepin-security` 这个名字非常的 generic，所以不同于其它 SIG 的创建，若保持此名称的话，此 SIG 的创建要求会高很多，也会涉及到更多的讨论。如果预期目的确实是创建发行版级别的、面向整个 deepin 开源社区的安全小组，那么是否可以一并提供下此小组核心成员的以往的安全相关活动的经历，用以背书此小组有能力作为安全团队来展开活动呢？

当然，如果您的目的只是在 deepin 社区创建一个和安全相关事项挂钩的小组，而不是像上面提到的“整个发行版、整个社区”程度的小组的话，那么另一个选项是给 SIG 改一个不是那么 generic 的名字，例如 `deepin-hust-security`。

下面的评注假定期望是前者。

2024-05-24 03:00 UTC, BLumia commented on sig/deepin-security/README.md
> +1. 向 [openatom_club@hust.edu.cn](mailto:openatom_club@hust.edu.cn) 发送邮件，标明申请加入 deepin-security SIG，并简单介绍申请加入的原因。
如果作为 `deepin-security` 这样发行版级别的 SIG，加入流程唯一且指向 hust 的邮箱并不合适。

2024-05-24 03:00 UTC, BLumia commented on sig/deepin-security/README.md
> +使用这个[链接](https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=8a9qd4a8-2870-44b5-8dbe-02831031acc7)加入飞书群组
为何选择了飞书？是否应当考虑更公开的渠道？

2024-05-27 07:33 UTC, jingfelix commented
Closed as we plans to rewrite the proposal with different goal and description.

2024-05-27 07:33 UTC, closed without merging