[新 SIG 提案] Deepin Security SIG
deepin-community/SIG pull request #427
Opened 2024-07-23 07:27 UTC by gglinxiao

## 创建原因

随着国产操作系统的普及和推广，操作系统的安全性变的尤为重要！本课题组目的为了保障Deepin系统的安全性，跟踪国内外最新漏洞资讯以及进行Deepin的漏洞修复。

## 仓库创建

此 SIG 需在 deepin-community 组织下创建如下仓库：

- sig-deepin-security

2024-07-23 07:35 UTC, BLumia requested changes, later dismissed
安全 SIG 被社区贡献者期待很久了，SIG 本身的各个介绍需要尽可能符合实际情况。下面列了一些问题和疑问，并不是所有的都要改但需要参考评估是否应当调整。

2024-07-23 07:35 UTC, BLumia commented on sig/deepin-security/README.md
> +随着国产操作系统的普及和推广，操作系统的安全性变的尤为重要！本课题组目的为了保障Deepin系统的安全性，跟踪国内外最新漏洞资讯以及进行Deepin的漏洞修复。
```suggestion
随着国产操作系统的普及和推广，操作系统的安全性变的尤为重要！本课题组目的为了保障deepin系统的安全性，跟踪国内外最新漏洞资讯以及进行deepin的漏洞修复。
```

deepin 作为专有名词时，首字母是小写的。下同。

2024-07-23 07:35 UTC, BLumia commented on sig/deepin-security/README.md
> +1. 在[sig-deepin-security](https://github.com/deepin-community/sig-deepin-security/issues)提交issues 说明想加入的原因
这个是实际加入方式吗？看上去是复制粘贴的其它SIG的方式，应当以实际情况为准。

2024-07-23 07:35 UTC, BLumia commented on sig/deepin-security/README.md
> +在[sig-deepin-security](https://github.com/deepin-community/sig-deepin-security)项目的[ISSUE区](https://github.com/deepin-community/sig-deepin-security/issues)进行主要的讨论。
同上，应当以实际情况为准。

2024-07-23 07:35 UTC, BLumia commented on sig/deepin-security/README.md
> +且后续会陆续建立实时聊天渠道。
如果现有的话建议直接写现有途径。另外需要特殊描述安全相关事项的交流与反馈途径吗？

2024-07-23 08:19 UTC, UTsweetyfish commented
这个 SIG 是否直接负责 deepin 的应急响应？

2024-07-23 08:33 UTC, Zeno-sole commented
@gglinxiao  安全修复流程、响应时间、披露流程等需要做一下详细说明

2024-07-23 08:34 UTC, UTsweetyfish reviewed
see comments

2024-07-23 08:34 UTC, UTsweetyfish commented on sig/deepin-security/README.md
> +3. 熟悉C语言且有相关的开发经验
和 C 语言有什么关系

2024-07-23 08:34 UTC, UTsweetyfish commented on sig/deepin-security/README.md
> +4. 最好有安全行业相关的经验
这个不是“最好”吧，应该是标准吧

2024-07-23 12:33 UTC, gglinxiao commented
> 这个 SIG 是否直接负责 deepin 的应急响应？

负责。本 sig 负责日常漏洞修复以及应急响应。

2024-07-23 12:36 UTC, gglinxiao commented
> @gglinxiao  安全修复流程、响应时间、披露流程等需要做一下详细说明

具体流程尚在商讨中。

2024-07-23 12:41 UTC, gglinxiao commented on sig/deepin-security/README.md
> +3. 熟悉C语言且有相关的开发经验
首先因系统软件包基本都是 C 开发，再者漏洞的修复可能会有无现成修复补丁的情况，故希望可以有一些开发编程能力。

2024-08-05 05:57 UTC, RevySR commented
> > @gglinxiao  安全修复流程、响应时间、披露流程等需要做一下详细说明
> 
> 具体流程尚在商讨中。

请问现在有更详细流程给出吗？

2024-09-10 02:02 UTC, gglinxiao commented
> > > @gglinxiao  安全修复流程、响应时间、披露流程等需要做一下详细说明
> > 
> > 
> > 具体流程尚在商讨中。
> 
> 请问现在有更详细流程给出吗？

相关漏洞处理流程已通过内部评审。且已发布在聊天频道，如有疑问可在频道交流。现申请pr合入

2024-09-10 06:01 UTC, UTsweetyfish commented
> 相关漏洞处理流程已通过内部评审。且已发布在聊天频道

转发了过来

[sec.zip](https://github.com/user-attachments/files/16940154/sec.zip)

2024-09-11 04:28 UTC, Avenger-285714 commented on sig/deepin-security/metadata.yml
> +name: Deepin Security SIG - Deepin安全课题组
按照deepin相关的命名规范，d是不是应该小写

2024-09-11 04:28 UTC, Avenger-285714 commented on sig/deepin-security/MEMBERS.md
> +- [qinzhiben11](https://github.com/qinzhiben11)
Please add:

 - [Avenger-285714](https://github.com/Avenger-285714)

2024-09-11 04:28 UTC, Avenger-285714 commented on sig/deepin-security/metadata.yml
> +    id: 48324979
Please add:

  - handle: Avenger-285714
    id: 60058876

2024-09-11 04:28 UTC, Avenger-285714 commented on sig/deepin-security/MEMBERS.md
> +## 小组成员
虽然别的sig也基本不遵循而且没有实质性的影响，但是建议按id的首字母顺序对名单重新排序，metadata.yml同理

2024-09-11 08:37 UTC, UTsweetyfish commented on sig/deepin-security/MEMBERS.md
> +- [zengwei2000](https://github.com/zengwei2000)
```suggestion
- [UTSweetyfish](github.com/UTSweetyfish)
- [zengwei2000](https://github.com/zengwei2000)
```

2024-09-11 09:31 UTC, UTsweetyfish commented on sig/deepin-security/metadata.yml
> +    id: 50387785
```suggestion
    id: 50387785
  - handle: UTSweetyfish
    id: 124018391
```

2024-09-14 03:28 UTC, BLumia approved these changes

2024-09-18 03:12 UTC, justforlxz approved these changes

2024-09-18 03:32 UTC, Zeno-sole commented
/approve

2024-09-18 03:37 UTC, Zeno-sole approved these changes

2024-09-18 04:47 UTC, RevySR approved these changes

2024-09-18 05:03 UTC, Avenger-285714 commented
/approve

2024-09-23 09:38 UTC, BLumia commented
正式决议发起于 9/14 Matrix TC 公开群，满足公示一个工作周（含五个工作日）内有至少1/3委员会成员同意且无反对票决议条件，予以合入。

2024-09-23 09:41 UTC, merged