[新 SIG 提案]Deepin Game Hub
deepin-community/SIG pull request #429
Opened 2024-07-30 14:53 UTC by 244099121

创建原因
随着国产操作系统的普及和推广，国产操作系统的娱乐以及游戏生态羸弱存在较大的游戏生态缺陷，本小组目的是为了向国产操作系统Deepin提供更多的基于原生以及WineHQ兼容层的游戏使用方案，以提升Deepin在国内外娱乐游戏方面的可用性和易用性。

仓库创建
此 SIG 需在 deepin-community 组织下创建如下仓库：
· Deepin-Game-Hub

2024-07-31 09:08 UTC, BLumia requested changes

2024-07-31 09:08 UTC, BLumia commented on sig/deepin-game-hub/metadata.yml
> +telegram：https://t.me/deepin
这里的冒号应当是半角冒号，否则会是无效的 YAML 文件。

2024-08-01 02:24 UTC, BLumia commented on sig/deepin-game-hub/metadata.yml
> +telegram: https://t.me/deepin
这个确认没问题吗？是我们英文语言国际群的地址？

2024-08-01 02:26 UTC, 244099121 reviewed
已经修改标点符号

2024-08-01 02:28 UTC, 244099121 commented on sig/deepin-game-hub/metadata.yml
> +telegram: https://t.me/deepin
没事的，陈给的，问璐要的。

2024-08-01 02:41 UTC, 244099121 reviewed
我已经取消了Telegram的链接，文件内的介绍存在一个官方的企业微信群，可以使用这个加群讨论

2024-08-01 02:51 UTC, BLumia commented on sig/deepin-game-hub/metadata.yml
> +date-archived: '2024/07/25'
这个是归档时间，小组已经废弃的日期。没废弃就留空。

2024-08-01 02:51 UTC, BLumia commented on sig/deepin-game-hub/metadata.yml
> +#telegram: https://t.me/deepin
```suggestion
```

本身也不对，直接删了吧

2024-08-01 02:51 UTC, BLumia commented on sig/deepin-game-hub/metadata.yml
> +    id: 123457
```suggestion
```

列表的用户和小组成员要一致，需要真实存在，不要留着模板上的假帐户。

2024-08-01 02:51 UTC, BLumia commented on sig/deepin-game-hub/README.md
> +deepin社区游戏板块（https://bbs.deepin.org/module/detail/201）
```suggestion
deepin社区游戏板块（<https://bbs.deepin.org/module/detail/201>）
```

避免 markdown 渲染引擎把后半个括号作为 url 的一部分渲染进去。

2024-08-01 02:51 UTC, BLumia commented on sig/deepin-game-hub/metadata.yml
> +    - sig-deepin-game-hub
这个是确认需要的吗？用处是小组博客？是的话，需要使用博客模板仓库吗？

2024-08-01 04:05 UTC, 244099121 commented on sig/deepin-game-hub/README.md
> +deepin社区游戏板块（https://bbs.deepin.org/module/detail/201）
改了哦

2024-08-01 05:08 UTC, BLumia approved these changes

2024-08-01 08:03 UTC, hudeng-go commented
/approve

2024-08-01 09:03 UTC, Zeno-sole commented
/approve

2024-08-05 05:56 UTC, RevySR commented on sig/deepin-game-hub/README.md
> +Telegram：https://t.me/deepin
没有单独sig的topic频道吗

2024-08-05 05:56 UTC, RevySR commented on sig/deepin-game-hub/metadata.yml
> +# 提交前请删除这些注释
？提交前请删除这些注释

2024-08-05 07:23 UTC, 244099121 commented on sig/deepin-game-hub/README.md
> +Telegram：https://t.me/deepin
暂时没有本小组由UOS/Deepin的运营人员实际管理

2024-08-05 07:25 UTC, 244099121 commented on sig/deepin-game-hub/metadata.yml
> +# 提交前请删除这些注释
删掉了

2024-08-05 09:37 UTC, BLumia commented on sig/deepin-game-hub/README.md
> +Telegram：https://t.me/deepin
那就暂时先移除这个？metadata.yml 里已经移除了，这里也应当一并移除。

2024-08-05 10:11 UTC, 244099121 commented
已经删除TG链接

2024-08-08 06:46 UTC, Zeno-sole commented
/approve

2024-08-08 06:49 UTC, justforlxz approved these changes

2024-08-08 06:54 UTC, BLumia commented
公示满一周，满足 1/3 TC 成员同意且无反对意见。合入处理。

2024-08-08 06:54 UTC, merged