[新 SIG 提案] deepin-raspberrypi  SIG
deepin-community/SIG pull request #433
Opened 2024-08-13 13:58 UTC by XXTX-TOP

deepin-raspberrypi SIG 小组致力于将 deepin 操作系统移植到 Raspberry Pi 平台上，并优化其性能和兼容性。我们的小组成员包括对 Linux 系统开发、嵌入式系统和开源社区有浓厚兴趣的开发者和爱好者。

我们的主要目标是：

移植与优化：将 deepin 操作系统无缝移植到 Raspberry Pi 平台，并进行性能优化和兼容性测试。
技术支持：提供详尽的技术文档和支持，帮助用户在 Raspberry Pi 上顺利运行 deepin。
社区建设：通过论坛、邮件列表和即时通讯工具，建立一个活跃的技术交流社区，分享经验和解决问题。
我们欢迎所有对 deepin 和 Raspberry Pi 感兴趣的朋友加入，共同推动项目的发展和进步。

2024-08-14 02:00 UTC, BLumia requested changes
一些修改建议和一些疑问。

2024-08-14 02:00 UTC, BLumia commented on sig/deepin-raspberrypi/README.md
> +- [GitHub 上的小组仓库](https://github.com/deepin-community/sig-xxxx)
xxx?

2024-08-14 02:00 UTC, BLumia commented on sig/deepin-raspberrypi/README.md
> +- **即时通讯工具**：如 Matrix 或 QQ 群、微信群，用于实时交流和快速反馈。
具体是哪里？

2024-08-14 02:00 UTC, BLumia commented on sig/deepin-raspberrypi/metadata.yml
> +    - sig-deepin-raspberrypi
这个仓库是要的吗？如果要，需要使用 https://github.com/deepin-community/sig-template 仓库作为模板吗？

2024-08-14 02:00 UTC, BLumia commented on sig/deepin-raspberrypi/metadata.yml
> +    - deepin-raspberrypi
这个是软件包仓库吗？

2024-08-14 05:34 UTC, XXTX-TOP commented on sig/deepin-raspberrypi/metadata.yml
> +    - deepin-raspberrypi
是的

2024-08-14 06:02 UTC, XXTX-TOP commented on sig/deepin-raspberrypi/metadata.yml
> +    - sig-deepin-raspberrypi
是的

2024-08-14 06:02 UTC, XXTX-TOP commented on sig/deepin-raspberrypi/README.md
> +- **即时通讯工具**：如 Matrix 或 QQ 群、微信群，用于实时交流和快速反馈。
微信群已创建

2024-08-14 06:02 UTC, XXTX-TOP commented on sig/deepin-raspberrypi/README.md
> +- [GitHub 上的小组仓库](https://github.com/deepin-community/sig-xxxx)
已修改

2024-08-14 06:09 UTC, BLumia requested changes
审视一下这个文档，这个文档最终会出现在 deepin 官网的 SIG 列表中，指向你的 SIG 的链接里，感兴趣的用户可能会试着根据你的描述来加入小组。这个文档的描述是否能够达到此目的？

2024-08-14 06:09 UTC, BLumia commented on sig/deepin-raspberrypi/README.md
> +- **即时通讯工具**：微信群用于实时交流和快速反馈。
这个文档的目的是“让看到这个文档的人能够通过你给出的描述找到你们并参与你们的活动”。你这里并没有任何指向相关讨论渠道的链接或者相关描述。

2024-08-14 06:18 UTC, XXTX-TOP commented on sig/deepin-raspberrypi/README.md
> +- **即时通讯工具**：微信群用于实时交流和快速反馈。
已更新群聊（QQ群：961470852）

2024-08-14 07:46 UTC, BLumia approved these changes

2024-08-22 03:24 UTC, XXTX-TOP commented
/merge

2024-08-22 05:20 UTC, Zeno-sole commented
/approve

2024-08-22 05:21 UTC, Zeno-sole approved these changes

2024-08-22 06:40 UTC, hudeng-go commented
/approve

2024-08-22 07:05 UTC, justforlxz approved these changes

2024-08-22 07:06 UTC, BLumia commented
公示满一周，满足 1/3 TC 成员同意且无反对意见。合入处理。

2024-08-22 07:06 UTC, merged