Create deepin-Fedora
deepin-community/SIG pull request #435
Opened 2024-09-12 08:49 UTC by Gytqxxtg

为Fedora操作系统适配和维护 Deepin Environment Desktop（简称：DDE），让Fedora系统的用户也能体验DDE。

2024-09-12 16:11 UTC, BLumia requested changes
请先参阅 https://github.com/deepin-community/SIG/blob/master/sig/README.zh_CN.md ，你没有提供创建 SIG 所需的必要信息。

2024-09-14 03:01 UTC, topazus commented
@Gytqxxtg Fedora打包也有deepinde-sig，https://src.fedoraproject.org/group/deepinde-sig 。但是没啥人维护。
你可以先成为Fedora官方包维护者，再加入deepinde-sig。打一些dde目前缺少的包，然后在redhat bugzilla审查通过。然后就能让Fedora系统的用户也能体验DDE。

2024-09-20 02:46 UTC, BLumia commented
https://github.com/deepin-community/SIG/pull/436 相关？

2024-10-09 05:28 UTC, BLumia commented
请考虑加入 https://github.com/deepin-community/SIG/pull/436 :)

2024-10-09 05:28 UTC, closed without merging