申请创建sig-Fedora
deepin-community/SIG pull request #436
Opened 2024-09-20 02:24 UTC by tekkamanninja

* add-sig

2024-09-20 02:45 UTC, BLumia requested changes
另外请问你们目前有加 dde-porting 小组或者在 dde-porting 小组的群里吗？你们的小组工作内容和 DDE 桌面环境的移植是强相关的，dde-porting 小组本身也会在必要的时候提供一些移植相关的注意事项，也会协助推进一些移植问题的解决。

（这个 request change 指的是下面列出的问题）

2024-09-20 02:45 UTC, BLumia commented on sig/Fedora/README.md
> +ps: 章程目前还不完善，有兴趣的同步可以加入讨论。
请按实际情况编写，不要照搬其它小组的章程。

2024-09-20 02:45 UTC, BLumia commented on sig/Fedora/metadata.yml
> +    id:
需要提供 id。提供方式在 metadata 模板中有注明。

2024-09-20 02:54 UTC, tekkamanninja commented on sig/Fedora/metadata.yml
> +    id:
好的，谢谢，我正在叫他们发给我

2024-09-20 02:56 UTC, tekkamanninja commented on sig/Fedora/README.md
> +ps: 章程目前还不完善，有兴趣的同步可以加入讨论。
我稍微改一下，马上

2024-09-20 08:45 UTC, BLumia submitted a review, later dismissed
正式开始 SIG 创建流程之前，我这边也确认下：

申请中提到的 sig-Fedora 这个仓库是确实需要的么？之前的 SIG 很多是申请了最终都没有在使用这么个仓库，sig-xxx 名字的仓库不是创建 SIG 的必要条件，所以你们可以按实际情况决定到底要不要创建，以及如果要的话，是否需要基于目前的[模板仓库](https://github.com/deepin-community/sig-template)创建（答复下我就好，当然如果答案是不需要的话，得一并更新下这个PR里的对应描述）。

2024-09-20 09:01 UTC, tekkamanninja commented
> 正式开始 SIG 创建流程之前，我这边也确认下：
> 
> 申请中提到的 sig-Fedora 这个仓库是确实需要的么？之前的 SIG 很多是申请了最终都没有在使用这么个仓库，sig-xxx 名字的仓库不是创建 SIG 的必要条件，所以你们可以按实际情况决定到底要不要创建，以及如果要的话，是否需要基于目前的[模板仓库](https://github.com/deepin-community/sig-template)创建（答复下我就好，当然如果答案是不需要的话，得一并更新下这个PR里的对应描述）。

需要，是您帮忙开一个  sig-Fedora 仓库， 然后把现在的小组成员加入进去作为维护人，我已经安排创建仓库内容了， 您这里创建好了，我们可以push上去

2024-09-20 09:07 UTC, wineee requested changes

2024-09-20 09:07 UTC, wineee commented on sig/Fedora/README.md
> +活动范围：deepin社区论坛、邮件列表、Telegram、matrix、Slack
这里需要给出具体的链接

2024-09-21 09:50 UTC, tekkamanninja commented on sig/Fedora/README.md
> +活动范围：deepin社区论坛、邮件列表、Telegram、matrix、Slack
好的 ， 我这就去setup，并补充link

2024-09-23 05:59 UTC, wineee requested changes

2024-09-23 05:59 UTC, wineee commented on sig/Fedora/metadata.yml
> +matrix:
我看提供了 matrix 群，这里也填一下

2024-09-23 05:59 UTC, wineee commented on sig/Fedora/README.md
> +1. 在Telegram 或 matrix 或者 Slack中预先沟通。
中文中的英文单词左右的空格统一一下，建议左右都有空格，如果有 Slack 要提供链接，没有要更新描述

2024-09-23 07:03 UTC, tekkamanninja commented on sig/Fedora/metadata.yml
> +matrix:
DONE

2024-09-23 07:03 UTC, tekkamanninja commented on sig/Fedora/README.md
> +1. 在Telegram 或 matrix 或者 Slack中预先沟通。
DONE

2024-09-23 07:59 UTC, wineee approved these changes

2024-09-23 07:59 UTC, topazus commented
@tekkamanninja Can I apply into the group? Fedora packager account: https://src.fedoraproject.org/user/topazus

2024-09-23 08:57 UTC, tekkamanninja commented
> @tekkamanninja Can I apply into the group? Fedora packager account: https://src.fedoraproject.org/user/topazus

sure, Could you make a PR , add you as a member after this is merged ?

2024-09-23 09:03 UTC, topazus commented
> sure, Could you make a PR , add you as a member after this is merged ?

Ok, I will.

2024-09-23 09:36 UTC, BLumia approved these changes

2024-09-23 10:12 UTC, shiptux commented
/approve

2024-09-23 14:48 UTC, felixonmars commented
/approve

2024-09-25 13:10 UTC, RevySR approved these changes

2024-10-08 10:07 UTC, justforlxz approved these changes

2024-10-09 03:12 UTC, Zeno-sole approved these changes

2024-10-09 04:49 UTC, BLumia commented
公示满一周，满足 1/3 TC 成员同意且无反对意见。合入处理。

2024-10-09 04:49 UTC, merged