[新 SIG 提案] SIG deepin-hardware-support
deepin-community/SIG pull request #50
Opened 2022-09-16 04:19 UTC by opsiff

添加硬件适配sig
仓库创建
[deepin-hardware-support-sig](https://github.com/linuxdeepin/deepin-hardware-support-sig)

2022-09-16 05:09 UTC, BLumia approved these changes

2022-09-16 05:09 UTC, BLumia commented on sig/deepin-hardware-support/MEMBERS.md
> +- [opsiff](https://github.com/opsiff)
小组人数不满足，应当至少有两人，不然很难展开活动

2022-09-16 05:09 UTC, BLumia commented on sig/deepin-hardware-support/README.md
> +# deepin-hardware-support SIG
这里可以写中文的，不必拘于 Xxx SIG 的格式

2022-09-16 05:09 UTC, BLumia commented on sig/deepin-hardware-support/README.md
> +[deepin-hardware-support-sig](https://github.com/linuxdeepin/deepin-hardware-support-sig)
sig- 放在最前面吧。别的 SIG 的仓库名称都是 sig- 在前面的格式，可以和别的组保持一致。

2022-09-16 05:09 UTC, BLumia commented on sig/deepin-hardware-support/README.md
> +必要时进行线上会议讨论相关问题。
这好像不是章程吧，这个内容应该是和 `如何加入` 那一节的内容重叠的，而其实我们并没有要求出现 `如何加入` 一节，具体可以看 [原始模板](https://github.com/deepin-community/SIG/tree/master/sig/.template.zh_CN) 的内容。

2022-09-16 05:10 UTC, BLumia requested changes
还是需要调整下内容的。

2022-09-16 05:32 UTC, zccrs commented on sig/deepin-hardware-support/MEMBERS.md
> +- [opsiff](https://github.com/opsiff)
可以加上 @tsic404  和 @Zeno-sole

2022-09-19 07:42 UTC, merged

2022-09-19 07:42 UTC, BLumia approved these changes
相关仓库已创建，相关人员已邀请