add Deepin en español
deepin-community/SIG pull request #52
Opened 2022-09-28 03:18 UTC by alvarosamudio

2022-09-28 11:39 UTC, BLumia requested changes
Hi!

Thanks for the interest, FYI the Special Interest Group in deepin-community must have a public and clear goal to achieve.  What does this SIG plans to do? Where does the discussion happens , etc. So you really need to fill the template to let other community contributors know about the SIG you'd like to create.

If you don't plan to achieve some kinds of goal but just want to create a end-user forum, then a SIG is not necessary to do so :)

If you still have any question, please feel free to let me know. Thanks!

2022-09-28 11:39 UTC, BLumia commented on sig/deepin-en-español/README.md
> +- [Other links](url)
You need to fill the template with the content about what does this SIG do.

2022-09-28 23:37 UTC, alvarosamudio commented on sig/deepin-en-español/README.md
> +- [Other links](url)
ok

2022-09-29 03:54 UTC, BLumia reviewed
Thanks for the update! Once the SIG get created, an associated git repo (`sig-deepin-in-spanish`) will be created which can be used to put the SIG work/goal showcase posts, and the Administrators will be invited to this organization so you guys can maintain that repo.

I might edit the title and description of this PR to ensure it fit the current SIG creation guideline, and I'll approve and merge this PR once I'm ready (probably later today) :)

2022-09-29 09:17 UTC, BLumia commented on sig/deepin-in-spanish/README.md
> +-[Telegram Group] (https://t.me/deepinenespanol)
```suggestion
- [Telegram Group](https://t.me/deepinenespanol)
```

2022-09-29 09:28 UTC, BLumia commented
Seems I cannot apply the change directly so you need to fix that by yourself. After that minor issue gets fixed, I'll approve and get this PR merged.

By the way, the related SIG team has already been created and I already invited the four admins to the team, so they can check their inbox and see if the invitation email is received.

Since SIG requires to have at least one post about the goals that the SIG had achieved quarterly, a SIG repo (https://github.com/deepin-community/sig-deepin-in-spanish) ([site](https://deepin-community.github.io/sig-deepin-in-spanish/)) was created for this purpose so you can put the related posts here. We haven't prepared an English version README file to get you started but it's just a regular [HUGO](https://gohugo.io/) site, so you can simply read the HUGO documentation to learn about how to use it. You can change the content in that repo freely as long as you needed, just make sure there is an RSS atom so we can subscribe :)

2022-09-29 15:09 UTC, BLumia approved these changes

2022-09-29 15:09 UTC, merged